### PR TITLE
use compiler options from compilation_commands.json

### PR DESCRIPTION
**Pull request by roccoblues**
Instead of calling the `include-what-you-use` binary directly we now use `iwyu_tool.py` which *really* parses the compilation database. This fixes a lot of the errors I was getting and should be much more portable.

**Quickstart for review**

```sh
# configure and make
./configure --compile-commands && make

# fix invalid json
tac compile_commands.json | sed '2 s/.$//' | tac > compile_commands.json.tmp && mv compile_commands.json.tmp compile_commands.json

# run on all files that we compile
cat compile_commands.json| jq -r '.[] | .file' | xargs ../iwyu/bin/iwyu.sh
```

**Caveats**

If we pass header files to the script it will output a warning that the file is not found in the compilation database.

### CODE REVIEW

**Comment by flatcap** [comment]
It fails for some python reason that I can't decipher.
(I saw the same error yesterday with playing with `iwyu_tool.py`)

```
$ iwyu.sh mview.c
Traceback (most recent call last):
  File "/usr/bin/iwyu_tool.py", line 500, in <module>
    sys.exit(_bootstrap(sys.argv))
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/iwyu_tool.py", line 495, in _bootstrap
    return main(args.dbpath, args.source, args.verbose,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/iwyu_tool.py", line 421, in main
    compilation_db = json.load(fileobj)
                     ^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 370 column 1 (char 360178)
```

Both: `compile_commands.json` and `mview.o.json` exist in the current directory.

**Comment by flatcap** [comment]
This isn't the problem, but the last argument is off:
```
iwyu_tool.py -p . mview.c -- -Xiwyu --pch_in_code -Xiwyu --no_comments -Xiwyu --mapping_file=iwyu.sh/imp/neomutt.imp
```

**Comment by roccoblues** [comment]
Did you do the JSON fix?

**Comment by flatcap** [comment]
sorry, no.
/me reads and tries

**Comment by roccoblues** [comment]
> This isn't the problem, but the last argument is off:
> 
> ```
> iwyu_tool.py -p . mview.c -- -Xiwyu --pch_in_code -Xiwyu --no_comments -Xiwyu --mapping_file=iwyu.sh/imp/neomutt.imp
> ```

ouch, this is probably because I call `iwyu.sh` with a full path.

**Comment by flatcap** [comment]
```
attach/attach.c should add these lines:
#include "attach/lib.h"

attach/attachments.c should add these lines:
#include "attach/lib.h"

attach/cid.c should add these lines:
#include "attach/lib.h"

attach/cid.c should remove these lines:
- #include "attach.h"
- #include "mutt_attach.h"

attach/dlg_attach.c should add these lines:
#include "attach/lib.h"

attach/dlg_attach.c should remove these lines:
- #include "attach.h"
- #include "attachments.h"
- #include "functions.h"
- #include "private_data.h"
- #include "recvattach.h"

attach/functions.c should add these lines:
#include "attach/lib.h"

attach/functions.c should remove these lines:
- #include "attach.h"
- #include "mutt_attach.h"
- #include "private_data.h"
- #include "recvattach.h"

attach/mutt_attach.c should add these lines:
#include "attach/lib.h"

attach/mutt_attach.c should remove these lines:
- #include "cid.h"

attach/private_data.c should add these lines:
#include "attach/lib.h"

attach/recvattach.c should add these lines:
#include "attach/lib.h"

attach/recvattach.c should remove these lines:
- #include "attach.h"
- #include "mutt_attach.h"

browser/private_data.c should add these lines:
#include "browser/lib.h"

color/command.c should remove these lines:
- #include "pager/lib.h"

conn/accountcmd.c should add these lines:
#include "conn/connaccount.h"

gui/mutt_curses.h should remove these lines:
- #include <ncursesw/ncurses.h>

gui/resize.c should remove these lines:
- #include <termios.h>

gui/terminal.c should remove these lines:
- #include <ncursesw/term.h>

history/dlg_history.c should add these lines:
#include "history/lib.h"

history/dlg_history.c should remove these lines:
- #include "functions.h"

history/functions.c should add these lines:
#include "history/lib.h"

mutt/notify.c should add these lines:
#include "mutt/notify_type.h"
#include "mutt/observer.h"

ncrypt/crypt_mod.c should add these lines:
#include "ncrypt/lib.h"

pager/private_data.c should add these lines:
#include "pager/lib.h"
```

**Comment by flatcap** [comment]
I've pushed some code fixes to [[devel/iwyu]](https://github.com/neomutt/neomutt/tree/devel/iwyu).
This takes me to:
- 566 correct
- one out-of-scope error for `/usr/include/gnutls/gnutls.h`
- one build warning for `mutt/md5.c`

The only flaw I see is the 98 header files that aren't checked.

```
address/idna2.h
address/lib.h
alias/lib.h
attach/lib.h
autocrypt/lib.h
autocrypt/private.h
bcache/lib.h
browser/lib.h
color/command2.h
color/curses2.h
color/lib.h
color/merged.h
color/notify2.h
color/regex4.h
color/simple2.h
complete/lib.h
compmbox/lib.h
compose/lib.h
compose/private.h
compress/lib.h
compress/private.h
config/inheritance.h
config/lib.h
config/regex2.h
config/sort2.h
config/types.h
conn/connection.h
conn/gsasl2.h
conn/lib.h
conn/private.h
conn/ssl.h
convert/lib.h
core/lib.h
core/mxapi.h
core/tmp.h
email/content.h
email/globals.h
email/lib.h
enter/lib.h
enter/wdata.h
envelope/lib.h
envelope/private.h
format_flags.h
functions.h
globals.h
gui/lib.h
gui/rootwin.h
hcache/lib.h
helpbar/lib.h
helpbar/private.h
history/lib.h
imap/lib.h
imap/private.h
index/ibar.h
index/lib.h
index/private.h
maildir/lib.h
maildir/private.h
mbox/lib.h
menu/lib.h
menu/private.h
mixmaster/lib.h
mixmaster/private_data.h
mixmaster/win_hosts.h
mutt.h
mutt/array.h
mutt/eqi.h
mutt/lib.h
mutt/logging2.h
mutt/message.h
mutt/notify_type.h
mutt/observer.h
mutt/regex3.h
mutt/signal2.h
mutt/string2.h
mutt_options.h
ncrypt/lib.h
ncrypt/private.h
nntp/lib.h
nntp/private.h
notmuch/lib.h
notmuch/private.h
pager/lib.h
parse/lib.h
parse/rc.h
pattern/lib.h
pattern/private.h
pop/lib.h
pop/private.h
postpone/lib.h
progress/lib.h
progress/window.h
protos.h
question/lib.h
send/lib.h
sidebar/lib.h
sidebar/private.h
store/lib.h
```

Edit: list reduced

**Comment by roccoblues** [comment]
Are you sure that they are not checked? I think if they are used `iwyu` checks them. For example:

```
../iwyu/bin/iwyu.sh address/*.c

(address/address.h has correct #includes/fwd-decls)

(address/address.c has correct #includes/fwd-decls)


(address/group.h has correct #includes/fwd-decls)

(address/group.c has correct #includes/fwd-decls)


(address/idna.c has correct #includes/fwd-decls)
```

The only ones that aren't checked are those that we never include.

**Comment by flatcap** [comment]
Excluding the debug code which I haven't built, I'm still left with 100 headers that aren't mentioned.

**Comment by flatcap** [comment]
Adding `#include <lmdb.h>` to `mutt/lib.h` doesn't trigger any warnings.

**Comment by roccoblues** [comment]
I think you're right: https://github.com/include-what-you-use/include-what-you-use/issues/1035#issue-1218476364

If I understand this correctly:
* works:  `address.c` -> `address.h`
* doesn't work: `address.c` -> `lib.h`   
* doesn't work: `address.c` -> `mutt/lib.h`

**Comment by flatcap** [comment]
Summary:
- 42 `lib.h`
  Library entry points
- 26 `misc.h`
  Headers without source, e.g. API definitions
- 16 `private.h`
  Library private data
- 14 `*2.h`
  Headers renamed to avoid clashes

**Comment by flatcap** [comment]
FYI: https://github.com/include-what-you-use/include-what-you-use/issues/268

Adding `-Xiwyu --check_also="*/lib.h"` seems to force checking the library headers, but gives a lot of junk output.
However running it on a source file that already includes one header does the checks we want.

```sh
iwyu_tool.py -p . commands.c -- -Xiwyu --pch_in_code -Xiwyu --no_comments -Xiwyu --mapping_file=neomutt.imp -Xiwyu --check_also="alias/lib.h"
```

outputs:

```
(alias/lib.h has correct #includes/fwd-decls)
(commands.h has correct #includes/fwd-decls)
(commands.c has correct #includes/fwd-decls)
```

**Comment by flatcap** [comment]
I've been poking around...
`compile_commands.json` contains exactly the same flags for every file.
This command extracts one line, for `main.c`, and collates the `-D` and `-I` options:

```sh 
grep -w "main.c" compile_commands.json | sed 's/\(.*\),/[\1]/' | jq '.[].arguments' | grep -A1 '"-[DI]"' | sed 's/[ ",]//g' | paste -s -d' '
```

The output (for Fedora Linux) is:
```
-D _ALL_SOURCE=1 -D _GNU_SOURCE=1 -D __EXTENSIONS__ -D _XOPEN_SOURCE_EXTENDED -I /usr/include/libassuan2 -I /usr/include -I /usr/include -I /usr/include -D NCURSES_WIDECHAR -I /usr/include/p11-kit-1 -I /include -I /usr/include/ -I /usr/include/qdbm -I /usr/include -I /usr/include -I /usr/include -I . -I . -D DEBUG -I ./test
```

Add our usual `-Xiwyu` options:
```
-Xiwyu --mapping_file=/PATH/imp/neomutt.imp
-Xiwyu --no_comments
-Xiwyu --pch_in_code
```

and we get a command-line that works for source and header files alike!
(manually wrapped, sorted and de-duped for effect :-)

```sh
include-what-you-use \
	-D DEBUG \
	-D NCURSES_WIDECHAR \
	-D _ALL_SOURCE=1 \
	-D _GNU_SOURCE=1 \
	-D _XOPEN_SOURCE_EXTENDED \
	-D __EXTENSIONS__ \
	-I . \
	-I test \
	-I /usr/include \
	-I /usr/include/libassuan2 \
	-I /usr/include/p11-kit-1 \
	-I /usr/include/qdbm \
	-Xiwyu --mapping_file=/PATH/TO/imp/neomutt.imp \
	-Xiwyu --no_comments \
	-Xiwyu --pch_in_code \
	mutt/file.h
```

Edit: fixed command

**Comment by roccoblues** [comment]
Your command didn't work for me: `open v3: no such file or directory` but I found a `jq` version:

```
tac compile_commands.json | sed '2 s/.$//' | tac | jq -r '.[] | select(.file=="main.c") .arguments as $args | $args | map(.=="-D" or .=="-I") | indices(true) | map($args[.] + " " + $args[.+1]) | unique | sort | join(" ")'
```

Output for macOS Ventura 13.5.1:
```
-D CMAKE_VERIFY_INTERFACE_HEADER_SETS=On -D NCURSES_WIDECHAR -D _ALL_SOURCE=1 -D _GNU_SOURCE=1 -D _XOPEN_SOURCE_EXTENDED -D __EXTENSIONS__ -I . -I ./test -I /opt/homebrew/Cellar/libidn2/2.3.4_1/include -I /opt/homebrew/Cellar/tokyo-cabinet/1.4.48/include -I /opt/homebrew/opt/ncurses/include -I /usr/local/include
```

Does my command work for you? Then I'd go ahead and change this MR.

**Comment by flatcap** [comment]
wow!  that's some advanced `jq`!

An alternative is to search and replace with `sed`.
This gives us valid 1-line json (without the need for `tac`)

```
sed -n '/\<main.c\>/s/\(.*\),/[\1]/p' compile_commands.json
```

combined with your `jq`, gives me:

```
sed -n '/\<main.c\>/s/\(.*\),/[\1]/p' compile_commands.json | jq -r '.[].arguments as $args | $args | map(.=="-D" or .=="-I") | indices(true) | map($args[.] + " " + $args[.+1]) | unique | sort | join(" ")'
```

Whichever version is fine.
Yes, please update the PR

**Comment by flatcap** [comment]
~update: I think your `jq`  `unique | sort` wants to be `sort | unique`~

**Comment by roccoblues** [comment]
With the new version I get this weird one:

```
../iwyu/bin/iwyu.sh address/lib.h

address/lib.h should add these lines:
#include "address/address.h"
#include "address/config_type.h"
#include "address/group.h"
#include "address/idna2.h"
```

**Comment by flatcap** [comment]
the mark up is meant to prevent that:
```
// IWYU pragma: begin_exports
...
// IWYU pragma: end_exports
```

It's a bit ugly, but changing the `lib.h` to explicit `keep`s works:

```c
#include "address.h"     // IWYU pragma: keep
#include "config_type.h" // IWYU pragma: keep
#include "group.h"       // IWYU pragma: keep
#include "idna2.h"       // IWYU pragma: keep
```

**Comment by roccoblues** [comment]
Oh then it should be `IWYU pragma: begin_keep` (https://github.com/include-what-you-use/include-what-you-use/blob/master/docs/IWYUPragmas.md#iwyu-pragma-begin_keepend_keep) with that it works:

```
../iwyu/bin/iwyu.sh address/lib.h

(address/lib.h has correct #includes/fwd-decls)
```

**Comment by flatcap** [comment]
yep, I spotted that
I'm converting and fixing the code now

**Comment by flatcap** [comment]
Hurrah!

Your new approach has turned up a lot of mistakes in the includes, which I've now fixed.
Including the `*/lib.h` ones.
I've also updated a lot of imp files.

NeoMutt builds locally, on freebsd (cirrus) and on macos (github).

Of the 686 files in my build, 683 have correct includes.

I still get a few errors (probably unfixable):

- `conn/openssl.c`
- `gui/mutt_curses.h`
- Two files outside of our build tree

Please can you give branch [[devel/iwyu]](https://github.com/neomutt/neomutt/tree/devel/iwyu) a try.

Thanks

**Comment by roccoblues** [comment]
Yes, this looks way better now! 🎉

I still get more errors but they seem to be because I don't build every feature and some macOS specific stuff. I posted the full output to https://github.com/neomutt/iwyu/issues/5.

**Review by flatcap — APPROVED** [review]
Briliiant!  Thanks!

**Pull request merged**
